trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'gke-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:
- stage: Lint
  jobs:
  - job: Lint
    displayName: 'Lint Stage'
    steps:
    - script: chmod +x ./gradlew
      displayName: 'Make Gradle Wrapper Executable'

    - script: ./gradlew checkstyleMain checkstyleTest
      displayName: 'Linting the code with Checkstyle'
