trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'terraform-gcp-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:


- stage: DeployToDevelopment
  displayName: Deploy to GKE (Development)
  jobs:
  - deployment: DeployToDev
    displayName: Deploy to Development Namespace
    environment: 'development-environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          
          - task: Kubernetes@1
            inputs:
              kubernetesServiceEndpoint: 'gke-connection'
              command: 'apply'
              arguments: '-f deployment --validate=false'








