trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'gke-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:
- stage: Lint
  jobs:
  - job: Lint
    displayName: 'Lint Stage'
    steps:
    - script: echo "Linting the code..."
      displayName: 'Linting the code with Checkstyle'


- stage: UnitTest
  jobs:
  - job: UnitTest
    steps:
    - script: |
        chmod +x ./gradlew
        ./gradlew test
      displayName: 'Running Unit Tests'


- stage: SonarQube
  jobs:
  - job: SonarQube
    displayName: 'SonarQube Stage'
    steps:
    - task: SonarQubePrepare@4
    #- script: ./gradlew sonarqube
      displayName: 'Running SonarQube Analysis'


- stage: BuildImage
  jobs:
  - job: BuildImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerHubServiceConnection)'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest

