trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'terraform-gcp-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'
  imagePullSecret: 'app-secret'
  GCP_KEY_FILE: './SA.json'

stages:


- stage: DeployToDevelopment
  displayName: Deploy to GKE (Development)
  jobs:
  - deployment: DeployToDev
    displayName: Deploy to Development Namespace
    environment: 'development-environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: |
              echo "Authenticating with Google Cloud..."
              gcloud auth activate-service-account --key-file=$(GCP_KEY_FILE)
              gcloud config set project spring-boot-project-431122
              gcloud container clusters get-credentials deployment-cluster --zone us-central1-a --project spring-boot-project-431122
            displayName: Authenticate and Get Cluster Credentials

          - script: |
              echo "Listing contents of $(System.DefaultWorkingDirectory)/deployment:"
              ls $(System.DefaultWorkingDirectory)/deployment
            displayName: List deployment directory contents

          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'development-environment-default-1722859931579'
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              command: 'apply'
              arguments: '-f $(System.DefaultWorkingDirectory)/deployment'
              workingDirectory: '$(System.DefaultWorkingDirectory)/deployment'
              outputFormat: 'yaml'







