trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'terraform-gcp-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:


- stage: DeployToDevelopment
  displayName: Deploy to GKE (Development)
  jobs:
  - deployment: DeployToDev
    displayName: Deploy to Development Namespace
    environment: 'development-environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: |
              echo "Listing contents of $(System.DefaultWorkingDirectory)/deployment:"
              ls $(System.DefaultWorkingDirectory)/deployment
            displayName: List deployment directory contents
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes (Development)
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'gke-connection'
              namespace: 'development'
              manifests: |
                $(System.DefaultWorkingDirectory)/deployment/namespaces.yml
                $(System.DefaultWorkingDirectory)/deployment/deployment-dev.yml
                $(System.DefaultWorkingDirectory)/deployment/service.yml
                $(System.DefaultWorkingDirectory)/deployment/ingress.yml
              validate: false





