trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'terraform-gcp-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:


- stage: DeployToDevelopment
  displayName: Deploy to GKE (Development)
  jobs:
  - deployment: DeployToDev
    displayName: Deploy to Development Namespace
    environment: 'development-environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: KubernetesManifest@0
            displayName: Create secret
            inputs: 
              action: createSecret
              secretType: dockerRegistry
              secretName: docker-secret
              dockerRegistryEndpoint: 'dockerhub-connection'
              kubernetesServiceConnection: 'gke-connection'
              namespace: default

          - task: KubernetesManifest@0
            displayName: Deploy
            inputs:
            kubernetesServiceConnection: 'gke-connection'
            namespace: default
            manifests: |
              deployment/deployment-dev.yml
            imagePullSecrets: |
              docker-secret








