trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'gke-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:
- stage: SetupDocker
  jobs:
  - job: SetupDocker
    steps:
    - script: |
        apt-get update
        apt-get install -y docker.io
        usermod -aG docker $(whoami)
      displayName: 'Install Docker'
    - script: |
        docker --version
        docker run hello-world
      displayName: 'Verify Docker Installation'