trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'gke-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:



- stage: PushImage
  jobs:
  - job: PushImage
    steps:
    - script:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerHubServiceConnection)'
        repository: '$(imageRepository)'
        Dockerfile: '$(dockerfilePath)'
        command: 'buildAndPush'
        tags: |
          $(tag)
          latest

- stage: PullImage
  jobs:
  - job: PullImage
    steps:
    - script: docker pull $(imageRepository):$(tag)
      displayName: 'Pulling Docker Image'

- stage: DeployInfrastructure
  jobs:
  - job: Terraform
    steps:
    - script: |
        terraform init
        terraform plan -out=tfplan
        terraform apply -input=false tfplan
      displayName: 'Deploying Infrastructure with Terraform'
      env:
        GOOGLE_CREDENTIALS: $(serviceConnectionJson) # Environment variable for GCP credentials
