trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'gke-connection'  # Service connection for GKE
  kubernetesServiceConnection: 'gke-connection'  # Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:
- stage: Lint
  jobs:
  - job: Lint
    steps:
    - script: ./gradlew checkstyleMain checkstyleTest
      displayName: 'Linting the code with Checkstyle'

- stage: UnitTest
  jobs:
  - job: UnitTest
    steps:
    - script: ./gradlew test
      displayName: 'Running Unit Tests'

- stage: SonarQube
  jobs:
  - job: SonarQube
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'SonarQube service connection'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'spring-boot-app'
        cliProjectName: 'spring-boot-app'
      displayName: 'Preparing SonarQube Analysis'
    - script: ./gradlew sonarqube
      displayName: 'Running SonarQube Analysis'

