trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'terraform-gcp-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:
- stage: DeployToDevelopment
  displayName: Deploy to GKE (Development)
  #dependsOn: DeployInfrastructure
  jobs:
  - deployment: DeployToDev
    displayName: Deploy to Development Namespace
    environment: 'development-environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes (Development)
            inputs:
              action: deploy
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              #namespace: development
              manifests: $(Pipeline.Workspace)/manifests/deployment/*.yaml



