trigger:
- dev
- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'terraform-gcp-connection' #Service connection for GKE
  kubernetesServiceConnection: 'gke-connection' #Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'

stages:


- stage: DeployToDevelopment
  displayName: Deploy to GKE (Development)
  #dependsOn: DeployInfrastructure
  jobs:
  - deployment: DeployToDev
    displayName: Deploy to Development Namespace
    environment: 'development-environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'manifests'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'
          - script: |
              kubectl apply -f $(System.ArtifactsDirectory)/deployment/namespaces.yml --insecure-skip-tls-verify
              kubectl apply -f $(System.ArtifactsDirectory)/deployment/deployment-dev.yml --insecure-skip-tls-verify
              kubectl apply -f $(System.ArtifactsDirectory)/deployment/service.yml --insecure-skip-tls-verify
              kubectl apply -f $(System.ArtifactsDirectory)/deployment/ingress.yml --insecure-skip-tls-verify
            displayName: Deploy to Kubernetes (Development)
    



