trigger:
- dev
#- main

pool: 'gcp host'

variables:
  dockerHubServiceConnection: 'dockerhub-connection'
  imageRepository: 'belalkhozeim22/spring-boot-app-image'
  dockerfilePath: './Dockerfile'
  tag: '$(Build.BuildId)'
  terraformServiceConnection: 'gke-connection'  # Service connection for GKE
  kubernetesServiceConnection: 'gke-connection'  # Same service connection for Kubernetes deployment
  terraformWorkingDirectory: './infrastructure'
stages:
- stage: PushImage
  jobs:
  - job: PushImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerHubServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: |
          $(tag)
          latest

- stage: PullImage
  jobs:
  - job: PullImage
    steps:
    - script: docker pull $(imageRepository):$(tag)
      displayName: 'Pulling Docker Image'

- stage: DeployInfrastructure
  jobs:
  - job: Terraform
    steps:
    - script: |
        terraform init
        terraform plan -out=tfplan
        terraform apply -input=false tfplan
      displayName: 'Deploying Infrastructure with Terraform'
      env:
        GOOGLE_CREDENTIALS: $(serviceConnectionJson) # Environment variable for GCP credentials

- stage: DeployToDevelopment
  dependsOn: DeployInfrastructure
  jobs:
  - deployment:
      displayName: Deploy to GKE (Development)
      environment: development
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes (Development)
              inputs:
                action: deploy
                kubernetesServiceConnection: $(kubernetesServiceConnection)
                namespace: development
                manifests: k8s/deployment-dev.yaml

- stage: DeployToProduction
  dependsOn: DeployInfrastructure
  jobs:
  - deployment:
      displayName: Deploy to GKE (Production)
      environment: production
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes (Production)
              inputs:
                action: deploy
                kubernetesServiceConnection: $(kubernetesServiceConnection)
                namespace: production
                manifests: k8s/deployment-prod.yaml

- stage: DeployToDevelopment
  dependsOn: DeployInfrastructure
  jobs:
  - deployment:
      displayName: Deploy to GKE (Development)
      environment: development
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes (Development)
              inputs:
                action: deploy
                kubernetesServiceConnection: $(kubernetesServiceConnection)
                namespace: development
                manifests: k8s/deployment-dev.yaml

- stage: DeployToProduction
  dependsOn: DeployInfrastructure
  jobs:
  - deployment:
      displayName: Deploy to GKE (Production)
      environment: production
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: KubernetesManifest@0
              displayName: Deploy to Kubernetes (Production)
              inputs:
                action: deploy
                kubernetesServiceConnection: $(kubernetesServiceConnection)
                namespace: production
                manifests: k8s/deployment-prod.yaml