apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      nodeSelector:
        nodepool: prod
      containers:
      - name: your-app
        image: your-docker-image:latest
        ports:
        - containerPort: 8080
