apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      nodeSelector:
        nodepool: dev
      containers:
      - name: your-app
        image: your-docker-image:latest
        ports:
        - containerPort: 8080
